#!/usr/bin/env php
<?php
/**
 * TripalDock Entry Point
 * ======================
 *
 * Register all commands using Symfony Console.
 */
// Constants
define("BASE_DIR", __DIR__);

// Load libraries
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} elseif (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
}

require __DIR__.'/src/bootstrap.php';

$package = json_decode(file_get_contents(BASE_DIR.'/composer.json'));

// Initiate application
$app = new \Symfony\Component\Console\Application('TripalDock', $package->version);
// Register commands
$app->add(new \StatonLab\TripalDock\NewCommand());

// Run the application
try {
    $app->run();
} catch (Exception $exception) {
    echo $exception->getMessage()."\n";
}
