#!/usr/bin/env bash

if [ -f .env ]; then
	source .env
fi

PS="$(docker-compose ps -q)"
if [ ! -z PS ]; then
	EXEC="yes"
else
	EXEC="no"
fi

# Run given commands
if [ $# -gt 0 ]; then

	if [ "$1" == "init" ]; then
		echo "TRIPALDOCK: Initializing ..."
		chmod +x tripaldock
		echo "TRIPALDOCK: Done. You may use the local version of tripaldock directly from this folder ./tripaldock COMMAND"
	elif [ "$1" == "ssh" ]; then

		if [ $EXEC == "yes" ]; then
			docker-compose exec app bash
		else
			docker-compose run --rm app bash
		fi

	elif [ "$1" == "up" ]; then
		docker-compose up -d

	elif [ "$1" == "down" ]; then
		docker-compose stop

	elif [ "$1" == "logs" ]; then
		if [ $# -eq 2 ]; then
			docker-compose logs "$2"
		else
			docker-compose logs
		fi

	elif [ "$1" == "install" ]; then
		if [ $# -lt 2 ]; then
			echo "TRIPALDOCK: Please specify the module name."
		else
			if [ "$2" == "elasticsearch" ]; then
				echo "TRIPALDOCK: Installing and enabling tripal elasticsearch including adding crontab entries and the downloading the php library"
				docker-compose exec app bash -c "/install-tripal-elasticsearch.sh"
			else
				echo "Installing and enabling $2"
				docker-compose exec app bash -c "cd /var/www/html && drush dl $2 -y && drush en $2 -y"
			fi
		fi
	elif [ "$1" == "rm" ]; then
		echo "Stopping and removing containers"
		docker-compose stop
		docker-compose rm -v
	fi
else
	echo "Please specify a command"
fi