#!/usr/bin/env bash

PS="$(docker-compose ps -q)"
if [ ! -z PS ]; then
	EXEC="yes"
else
	EXEC="no"
fi

function help() {
	echo "Available Commands:"
	echo "   init: Prepare local tripaldock script\n"
	echo "   ssh: Access the docker container with an interactive shell\n"
	echo "   up: Start all containers\n"
	echo "   down: Stop all containers\n"
	echo "   drush (required)[args]:"
	echo "      Run drush commands"
	echo "      [args]: any drush arguments such as pm-enable\n"
	echo "   install (required)[module]:"
	echo "      Installs, enables and configures a Drupal module"
	echo "      [module]: machine name of a module such as tripal_elasticsearch\n"
	echo "   logs (optional)[service]:"
	echo "      Display logs for all available services or only the specified service"
	echo "      [service]: one of app, postgres, or elasticsearch"
	echo "                   app: Apache and PHP logs"
	echo "                   postgres: Database logs"
	echo "                   elasticsearch: Elasticsearch logs\n"
}

WORKING_DIR=`pwd`
SCRIPT_DIR=`dirname $0`
DB_NAME=`cat docker-compose.yaml | grep POSTGRES_DB | awk -F"=" '{print $2}'`
DB_PASS=`cat docker-compose.yaml | grep POSTGRES_PASSWORD | awk -F"=" '{print $2}'`

cd $SCRIPT_DIR

# Run given commands
if [ $# -gt 0 ]; then

	if [ "$1" == "init" ]; then
		echo "TRIPALDOCK: Initializing ..."
		chmod +x tripaldock
		echo "TRIPALDOCK: Done. You may use the local version of tripaldock directly from this folder ./tripaldock COMMAND"
	elif [ "$1" == "ssh" ]; then

		if [ $EXEC == "yes" ]; then
			docker-compose exec app bash
		else
			docker-compose run --rm app bash
		fi

	elif [ "$1" == "up" ]; then
		docker-compose up -d

	elif [ "$1" == "down" ]; then
		docker-compose down

	elif [ "$1" == "logs" ]; then
		if [ $# -eq 2 ]; then
			docker-compose logs "$2"
		else
			docker-compose logs
		fi

	elif [ "$1" == "install" ]; then
		if [ $# -lt 2 ]; then
			echo "TRIPALDOCK: Please specify the module name."
		else
			if [ "$2" == "tripal_elasticsearch" ]; then
				echo "TRIPALDOCK: Installing and enabling tripal elasticsearch including adding crontab entries and the downloading the php library"
				docker-compose exec app bash -c "/install-tripal-elasticsearch.sh"
			else
				echo "TRIPALDOCK: Installing and enabling $2"
				docker-compose exec app bash -c "cd /var/www/html && drush dl $2 -y && drush en $2 -y"
			fi
		fi
	elif [ "$1" == "drush" ]; then
		shift 1
        CMD="drush $@ --root=/var/www/html"
        echo "TRIPALDOCK: Running $CMD"
	 	docker-compose exec app bash -ic "$CMD"

	elif [ "$1" == "self-update" ]; then
		echo "TRIPALDOCK: Updating statonlab/tripaldock"
		VENDOR_DIR=`composer global config --absolute vendor-dir`
		composer global require statonlab/tripaldock
		echo "TRIPALDOCK: Copying new files"
		cp -r "$VENDOR_DIR/statonlab/tripaldock/docker-files/docker" .
		cp "$VENDOR_DIR/statonlab/tripaldock/docker-files/tripaldock-bash" ./tripaldock
		./tripaldock init
#		echo "TRIPALDOCK: Would you like to replace your docker-compose.yaml file with a new one?"
#		select yn in "Yes" "No"; do
#  		  case $yn in
#        	Yes ) cp ~/.composer/vendor/statonlab/tripaldock/docker-files/docker-compose.yaml .; break;;
#        	No ) echo "";;
#    	  esac
#		done
		docker-compose up -d --build
		echo "TRIPALDOCK: Done."

	elif [ "$1" == "psql" ]; then
		shift 1
		echo "TRIPALDOCK: Connecting to postgres"
        docker-compose run --rm -e PGPASSWORD=$DB_PASS postgres psql -h postgres -U tripal -d $DB_NAME "$@"

	elif [ "$1" == "pg_dump" ]; then
		shift 1
        docker-compose run --rm -e PGPASSWORD=$DB_PASS postgres pg_dump -h postgres -U tripal -d $DB_NAME "$@"

	elif [ "$1" == "pg_restore" ]; then
		shift 1
		echo "TRIPALDOCK: Restoring DB $DB_NAME"
        docker-compose run --rm -e PGPASSWORD=$DB_PASS postgres pg_restore -h postgres -U tripal -d $DB_NAME "$@"

	elif [ "$1" == "rm" ]; then
		echo "Stopping and removing containers"
		docker-compose down -v
	else
		help
	fi
else
	echo "Please specify a command"
	echo "\n"
	help
fi

cd $WORKING_DIR
