#!/usr/bin/env bash

if [ -f .env ]; then
	source .env
fi

# Run given commands
if [ $# -gt 0 ]; then
	if [ "$1" == "init" ]; then
		echo "TRIPALDOCK: Initializing ..."
		chmod +x tripaldock
	fi
else
	echo "Please specify a command"
fi